src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: "text", length: 65535, nullable: true)]
    private ?string $beschreibung = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $datum = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $bild = null;

    #[ORM\ManyToOne(targetEntity: 'App\Entity\Kategorie', inversedBy: 'event')]
    private ?Kategorie $Kategorie = null;

    #[ORM\Column(nullable: true)]
    private ?int $anzahl = null;

    #[ORM\Column(nullable: true)]
    private ?int $max = null;


    #[ORM\Column(length: 255, nullable: true)]
    private ?string $zeit = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $hinweis = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $code = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ref = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $minteilnehmer = null;

    #[ORM\Column]
    private ?bool $active = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getRef(): ?string
    {
        return $this->ref;
    }

    public function setRef(string $ref): static
    {

        $this->ref = $ref;

        return $this;
    }

    public function getBeschreibung(): ?string
    {
        return $this->beschreibung;
    }

    public function setBeschreibung(?string $beschreibung): static
    {
        $this->beschreibung = $beschreibung;

        return $this;
    }

    public function getDatum(): ?string
    {
        return $this->datum;
    }

    public function setDatum(?string $datum): static
    {
        $this->datum = $datum;

        return $this;
    }

    public function getBild(): ?string
    {
        return $this->bild;
    }

    public function setBild(?string $bild): static
    {
        $this->bild = $bild;

        return $this;
    }

    public function getKategorie(): ?Kategorie
    {
        return $this->Kategorie;
    }

    public function setKategorie(?Kategorie $Kategorie): static
    {
        $this->Kategorie = $Kategorie;

        return $this;
    }

    public function getAnzahl(): ?int
    {
        return $this->anzahl;
    }

    public function setAnzahl(?int $anzahl): static
    {
        $this->anzahl = $anzahl;

        return $this;
    }

    public function getMax(): ?int
    {
        return $this->max;
    }

    public function setMax(?int $max): static
    {
        $this->max = $max;

        return $this;
    }

    public function getZeit(): ?string
    {
        return $this->zeit;
    }

    public function setZeit(?string $zeit): static
    {
        $this->zeit = $zeit;

        return $this;
    }

    public function getHinweis(): ?string
    {
        return $this->hinweis;
    }

    public function setHinweis(?string $hinweis): static
    {
        $this->hinweis = $hinweis;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getminteilnehmer(): ?string
    {
        return $this->minteilnehmer;
    }

    public function setminteilnehmer(?string $minteilnehmer): static
    {
        $this->minteilnehmer = $minteilnehmer;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): static
    {
        $this->active = $active;
        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use App\Entity\Kategorie;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('beschreibung')
            ->add('Kategorie', EntityType::class,['class'=>Kategorie::class])
            ->add('datum')
            ->add('zeit')
            ->add('hinweis')
            ->add('bild', FileType::class)
            ->add('speichern', SubmitType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Config\DoctrineConfig;

#[Route('/event', name: 'event.')]
class EventController extends AbstractController
{
    #[Route('/', name: 'liste')]
    public function index(EventRepository $ev): Response
    {
        $events = $ev->findAll();

        return $this->render('event/index.html.twig', [
            'events' => $events,
        ]);
    }

    #[Route('/anlegen', name: 'anlegen')]
    public function anlegen(ManagerRegistry $doctrine, Request $request): Response
    {
        $event = new Event();
        // Formular
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted()){
            // EntityManager
            $em = $doctrine->getManager();

            $bild = $request->files->get('event')['bild'];

            if($bild){
                $dateiname = md5(uniqid()). '.' .$bild->guessClientExtension();
            }

            $bild->move(
                $this->getParameter('bilder_ordner'),
                $dateiname
            );

            $event->setBild($dateiname);

            $em->persist($event);
            $em->flush();

            return $this->redirect($this->generateUrl('event.liste'));
        }
        return $this->render('event/anlegen.html.twig', [
            'anlegenForm' => $form->createView(),
        ]);
    }
    #[Route('/entfernen/{id}', name: 'entfernen')]
    public function entfernen($id, EventRepository $ev, ManagerRegistry $doctrine){
        // EntityManager
        $em = $doctrine->getManager();
        $event = $ev->find($id);
        $em->remove($event);
        $em->flush();

        $this->addFlash('Erfolg', 'Event wurde erfolgreich entfernt.');

        return $this->redirect($this->generateUrl('event.liste'));
    }
    #[Route('/anzeigen/{id}', name: 'anzeigen')]
    public function anzeigen(Event $event){
        return $this->render('event/anzeigen.html.twig', [
            'events' => $event,
        ]);
    }

}

templates/event/anlegen.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello anlegen!{% endblock %}

{% block body %}
<br>
    <div class="container">
        {{ form(anlegenForm) }}
    </div>
{% endblock %}

templates/event/anzeigen.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello anlegen!{% endblock %}

{% block body %}

    <div class="container-sm">
        <div class="row">
            <div class="col-4"></div>
            <div class="card mb-5 ">
                <img src="{{ asset('bilder/' ~ events.bild) }}" class="rounded img-thumbnail">
                <div class="card-body">
                    <h5 class="card-title">{{ events.name }}</h5>
                    <p class="card-text">{{ events.beschreibung|raw }}</p>

                </div>
                <div class="card" >
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Am: {{ events.datum|date("d.m.y") }}</li>
                        <li class="list-group-item">Um: {{ events.zeit }} Uhr</li>
                        <li class="list-group-item">Freie Plätze: {{ events.anzahl }}</li>
                        {% if events.hinweis == not null %}
                            <li class="list-group-item text-danger">{{ events.hinweis }}
                                {% if events.code == not null %}
                                    <br> <small>CODE FÜR ANMELDUNG BENÖTIGT</small>
                                {% endif %}
                            </li>
                        {% endif %}

                    </ul>
                </div>
                <div class="card-footer">
                    <a class="btn btn-outline-primary mt-2"
                       href="{{ path('app_anmelden', {id: events.id}) }}">Anmelden</a>
                    <a class="btn btn-outline-primary mt-2" href="{{ path('app_menu') }}">Zurück</a>
                </div>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EventController!{% endblock %}

{% block body %}
    {% for message in app.flashes('Erfolg') %}
        <div class="allert alert-success">
            <h3>{{ message }}</h3>
        </div>
    {% endfor %}
    <br>
    <div class="container">
        <h2>Events bearbeiten</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <td>
                        Nr
                    </td>
                    <td>
                        Titel
                    </td>
                    <td>
                        Beschreibung
                    </td>
                    <td>
                        Kategorie
                    </td>
                    <td>
                        Datum
                    </td>
                    <td>
                        Bild
                    </td>
                    <td>
                        Löschen
                    </td>
                    <td>
                        <a href="{{ path('event.anlegen') }}">Anlegen</a>
                    </td>
                </tr>
            </thead>
            <tbody>
            {% for event in events %}
                <tr>
                    <td>
                        {{ event.id }}
                    </td>
                    <td>
                        <a href="{{ path('event.anzeigen',{id: event.id}) }}">{{ event.name}}</a>
                    </td>
                    <td>
                        {{ event.beschreibung }}
                    </td>
                    <td>
                        {{ event.kategorie }}
                    </td>
                    <td>
                        {{ event.datum }}
                    </td>
                    <td>
                        {{ event.bild }}
                    </td>
                    <td class="align-content-center">
                        <a href="{{ path('event.entfernen',{id: event.id}) }}">Löschen</a>
                    </td>
                    <td>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}