src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookingRepository::class)]
class Booking
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $beginAt = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?int $maxParticipant = null;

    #[ORM\Column(nullable: true)]
    private ?int $minParticipant = null;

    #[ORM\Column(nullable: true)]
    private ?int $currentParticipant = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $speaker = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isActive = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $notice = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $code = null;

    #[ORM\Column(nullable: true)]
    private ?int $category_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getBeginAt(): ?\DateTimeImmutable
    {
        return $this->beginAt;
    }

    public function setBeginAt(\DateTimeImmutable $beginAt): static
    {
        $this->beginAt = $beginAt;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getMaxParticipant(): ?int
    {
        return $this->maxParticipant;
    }

    public function setMaxParticipant(?int $maxParticipant): static
    {
        $this->maxParticipant = $maxParticipant;

        return $this;
    }

    public function getMinParticipant(): ?int
    {
        return $this->minParticipant;
    }

    public function setMinParticipant(?int $minParticipant): static
    {
        $this->minParticipant = $minParticipant;

        return $this;
    }

    public function getCurrentParticipant(): ?int
    {
        return $this->currentParticipant;
    }

    public function setCurrentParticipant(?int $currentParticipant): static
    {
        $this->currentParticipant = $currentParticipant;

        return $this;
    }

    public function getSpeaker(): ?string
    {
        return $this->speaker;
    }

    public function setSpeaker(?string $speaker): static
    {
        $this->speaker = $speaker;

        return $this;
    }

    public function getIsActive()
    {
        return $this->isActive;
    }

    public function setIsActive($isActive): static
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getNotice(): ?string
    {
        return $this->notice;
    }

    public function setNotice(?string $notice): static
    {
        $this->notice = $notice;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getCategoryId(): ?int
    {
        return $this->category_id;
    }

    public function setCategoryId(?int $category_id): static
    {
        $this->category_id = $category_id;

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('beginAt')
            ->add('description')
            ->add('maxParticipant')
            ->add('minParticipant')
            ->add('currentParticipant')
            ->add('speaker')
            ->add('isActive')
            ->add('picture')
            ->add('notice')
            ->add('code')
            ->add('category_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Form\BookingType;
use App\Repository\BookingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/booking')]
class BookingController extends AbstractController
{
    #[Route('/', name: 'app_booking_index', methods: ['GET'])]
    public function index(BookingRepository $bookingRepository): Response
    {
        return $this->render('booking/index.html.twig', [
            'bookings' => $bookingRepository->findAll(),
        ]);
    }

    #[Route(path: '/calendar', name: "app_booking_calendar", methods: ['GET'])]
    public function calendar(): Response
    {
        return $this->render('booking/calendar.html.twig');
    }


    #[Route('/new', name: 'app_booking_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($booking);
            $entityManager->flush();

            return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('booking/new.html.twig', [
            'booking' => $booking,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_booking_show', methods: ['GET'])]
    public function show(Booking $booking): Response
    {
        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_booking_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Booking $booking, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('booking/edit.html.twig', [
            'booking' => $booking,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_booking_delete', methods: ['POST'])]
    public function delete(Request $request, Booking $booking, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$booking->getId(), $request->request->get('_token'))) {
            $entityManager->remove($booking);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/booking/_delete_form.html.twig
<form method="post" action="{{ path('app_booking_delete', {'id': booking.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ booking.id) }}">
    <button class="btn">Delete</button>
</form>

templates/booking/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/booking/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Booking{% endblock %}

{% block body %}
    <h1>Edit Booking</h1>

    {{ include('booking/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_booking_index') }}">back to list</a>

    {{ include('booking/_delete_form.html.twig') }}
{% endblock %}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking index{% endblock %}

{% block body %}
    <h1>Booking index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>BeginAt</th>
                <th>Description</th>
                <th>MaxParticipant</th>
                <th>MinParticipant</th>
                <th>CurrentParticipant</th>
                <th>Speaker</th>
                <th>IsActive</th>
                <th>Picture</th>
                <th>Notice</th>
                <th>Code</th>
                <th>Category_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for booking in bookings %}
            <tr>
                <td>{{ booking.id }}</td>
                <td>{{ booking.title }}</td>
                <td>{{ booking.beginAt ? booking.beginAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ booking.description }}</td>
                <td>{{ booking.maxParticipant }}</td>
                <td>{{ booking.minParticipant }}</td>
                <td>{{ booking.currentParticipant }}</td>
                <td>{{ booking.speaker }}</td>
                <td>{{ booking.isActive }}</td>
                <td>{{ booking.picture }}</td>
                <td>{{ booking.notice }}</td>
                <td>{{ booking.code }}</td>
                <td>{{ booking.categoryId }}</td>
                <td>
                    <a href="{{ path('app_booking_show', {'id': booking.id}) }}">show</a>
                    <a href="{{ path('app_booking_edit', {'id': booking.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_booking_new') }}">Create new</a>
{% endblock %}

templates/booking/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Booking{% endblock %}

{% block body %}
    <div class="container-fluid">
    <h1>Create new Booking</h1>

    {{ include('booking/_form.html.twig') }}

    <a href="{{ path('app_booking_index') }}">back to list</a>
    </div>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking{% endblock %}

{% block body %}
    <h1>Booking</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ booking.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ booking.title }}</td>
            </tr>
            <tr>
                <th>BeginAt</th>
                <td>{{ booking.beginAt ? booking.beginAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ booking.description }}</td>
            </tr>
            <tr>
                <th>MaxParticipant</th>
                <td>{{ booking.maxParticipant }}</td>
            </tr>
            <tr>
                <th>MinParticipant</th>
                <td>{{ booking.minParticipant }}</td>
            </tr>
            <tr>
                <th>CurrentParticipant</th>
                <td>{{ booking.currentParticipant }}</td>
            </tr>
            <tr>
                <th>Speaker</th>
                <td>{{ booking.speaker }}</td>
            </tr>
            <tr>
                <th>IsActive</th>
                <td>{{ booking.isActive }}</td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>{{ booking.picture }}</td>
            </tr>
            <tr>
                <th>Notice</th>
                <td>{{ booking.notice }}</td>
            </tr>
            <tr>
                <th>Code</th>
                <td>{{ booking.code }}</td>
            </tr>
            <tr>
                <th>Category_id</th>
                <td>{{ booking.categoryId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_booking_index') }}">back to list</a>

    <a href="{{ path('app_booking_edit', {'id': booking.id}) }}">edit</a>

    {{ include('booking/_delete_form.html.twig') }}
{% endblock %}